### ISSUE TITLE
stderr doesn't print raw

### ISSUE THREAD

**Issue by lhns** [jqlang/jq#2063] opened 2020-02-19 12:52 UTC
**Describe the bug**
stderr doesn't print its input as a raw string but as an escaped json string.

**To Reproduce**
```sh
jq -n '"line1\nline2" | stderr | empty'
```
Outputs ```"line1\nline2"```

**Expected behavior**
As the manual states:
> **stderr**
> Prints its input in **raw** and compact mode to stderr with no additional decoration, not even a newline.

I expected the program to output be:
```
line1
line2
```

**Environment (please complete the following information):**
 - OS and Version: Redhat Enterprise Linux 6
 - jq version 1.6

**Comment by nicowilliams** [comment] 2020-02-20 20:50
This is not a bug, but a feature.  Perhaps `stderr` should output raw when jq is in raw output mode, or perhaps we need a new `rawstderr` builtin.  Or perhaps we can leave this to the I/O work we're doing, and then the user can open `/dev/null` in raw mode.

**Comment by ajasmin** [comment] 2020-12-16 03:21
The documentation is misleading

> stderr
> Prints its input in *raw* and *compact* mode to stderr with no additional decoration, not even a newline.

Would let you believe that stderr behave like `--raw-output` and `--compact-output`
yet
- Unlike with `--raw-output`, strings on stderr are printed as JSON string 
- Unlike with `--compact-output`, stderr output are not separated by "\n"

**Comment by vergenzt** [comment] 2021-11-09 17:52
Yeah this is a bug IMO -- either the behavior or the documentation should be fixed, because right now they're inconsistent.

**Comment by hyperupcall** [comment] 2022-04-13 20:40
I am really enjoying jq - unfortunately I tripped up on this as well

I perused the docs quite extensively and it seems there is no way to print an arbitrary string (with escape sequences) to standard error?

I can't use `stderr` because newlines of its input are automatically escaped. `halt_error` prints the way I want, but it halts the program. The only way I have been able to print a newline to stderr is through `debug` - its an unfortunate unaesthetic workaround, but it works.

I don't think that the behavior of `stderr` should change based on if jq is in raw mode. If it is not possible in one way or another, I would welcome another function that yields the expected behavior.

**Comment by danfuzz** [comment] 2022-06-21 23:29
Just wanted to register a `+1` on folks who have run into this surprising behavior.

**Comment by rjbell4** [comment] 2022-11-16 23:29
`+1` from me, too.  I was really hoping to provide a customized warning, but since I cannot get `stderr` to actually create a newline, I guess I'm stuck with `debug`.

**Comment by jasonk** [comment] 2023-01-25 18:54
FWIW, I ended up here because I was trying to do something like this:

```
. as $line | try fromjson catch $line | stderr
```

I'm filtering ndjson logs and wanted to be able to use the `try fromjson` to filter valid json log lines that I could then pipe into further transforms, and wanted to be able to just redirect malformed lines to stderr

**Closed** 2023-07-23 22:06 UTC
Labels: bug
