### ISSUE TITLE
New definition for `repeat' 

### ISSUE THREAD

**Issue by fadado** [jqlang/jq#1715] opened 2018-09-03 09:28 UTC
In JQ the expression `repeat(empty)` diverges. To emulate  the repeat operator semantics in Icon the function `repeat` shoult be defined as:

```
def repeat(exp):
    def _repeat: 
        exp, _repeat;
    select(isempty(exp)|not)) | _repeat
;
```

**Comment by emanuele6** [comment] 2023-10-04 19:16
`select(isempty(exp)|not)) | _repeat` is not a good fix, a bunch of functions in jq have side effects, you cannot just call `isempty` on an arbitrary expression: `stderr`, `debug`, `error`, `now`, `input`, `inputs`, etc.
It is not even uncommon to use an expression with side effects with `repeat/1`: `repeat(input)`, `repeat([ input, input ])`, `repeat(now)`. Also pretty much all the ICON examples with `repeat` I was able to find were using it as `repeat case Event() ...`. That implementation just can't work: you will end up skipping the first line, or printing an extra time to stderr, etc.

The correct way to do what you are trying to do could be:
```jq
def repeat(exp):
    def _repeat:
        exp, _repeat;
    . as $dot |
    foreach ((exp | [ . ]), null) as $x (
        false;
        if $x then true end;
        if $x then $x[] else select(.) | $dot | _repeat end
    )
;
```

I also cannot find a reference for ICON's `repeat` that describes its behaviour.
Does it really only stop running if the first `exp` does not return any value as you are saying? I think it would be more plausible that it stops at the first `exp` that does not return any value, if it really does not run indefinitely like in jq, but I don't have a way to verify this.

Possible implementation for that behaviour:
```jq
def repeat(exp):
    . as $dot |
    def _repeat:
        foreach ((exp | [ . ]), null) as $x (
            false;
            if $x then true end;
            if $x then $x[] else select(.) | $dot | _repeat end
        );
    _repeat
;
```

But that would be rather different from the way `repeat/1` currently works in jq.

Anyway, `repeat(empty)` is working as documented. `repeat(exp)` repeatedly runs `exp` with the same input, until an error is raised.

**Comment by emanuele6** [comment] 2023-10-04 19:53
> But that would be rather different from the way `repeat/1` currently works in jq.

Well, realistically, if your `repeat/1` expression at some point retuns no values, it will also return no value the following times you run it and it will end up looping infinitely. Likely caused by a programming mistake.

I think the only possible case in which it does not is if your expression is something crazy like `repeat(select(now % 2))` that may return nothing based on the value of `now`.

So it may be beneficial to change the behaviour to make `repeat` stop looping not only when an error is thrown, but also the first time the expression returns nothing. But adding that change does not feel right.

**Comment by nicowilliams** [comment] 2023-10-04 22:19
Yes, it'd be nice if when `exp` is `empty` `repeat` does also.

**Comment by emanuele6** [comment] 2023-10-05 03:42
But how will I write my "Merry Christmas!" script then? D:

```jq
first(
   "Merry Christmas!" |
   repeat(now) as $now |
   select($now >= 1703458800)
)
```

instead of
```jq
first(
    "Merry Christmas!" |
    repeat(select(now >= 1703458800))
)
```
? :(

---

Yes, I think that would be nice, `repeat/1` returning nothing at one iteration and then something at the next is possible, but very unlikely. If `exp` returns `empty` it will likely be a infinite loop. So we could change that.

It would be nice to find a online reference that describes how `repeat` works in ICON to double check it actually works as I think it does; https://www2.cs.arizona.edu/icon/ does not have it.

**Comment by nicowilliams** [comment] 2023-10-05 03:59
> It would be nice to find a online reference that describes how `repeat` works in ICON to double check it actually works as I think it does; https://www2.cs.arizona.edu/icon/ does not have it.

You're in luck.  I have a copy of the second edition of The Icon Programming Language, which mentions `repeat` on pages 20 and 286, and it says:

![icon-repeat-pg20](https://github.com/jqlang/jq/assets/604851/2b114332-623a-4c97-a06b-ca67f8051ef6)
![icon-repeat-pg286](https://github.com/jqlang/jq/assets/604851/ddd1fade-2d8f-4b92-be12-436b8b6bb71e)

I.e., it's the same as jq's.

**Comment by emanuele6** [comment] 2023-10-05 03:59
I found https://archive.org/details/Griswold_Icon_1996/ on the internet archive.

From its description, it seems to work exactly like in `jq`
![file](https://github.com/jqlang/jq/assets/20175435/078abdda-a7bc-4915-9de1-37f85968e0a1)

**Comment by emanuele6** [comment] 2023-10-05 03:59
@nicowilliams hehe

**Comment by nicowilliams** [comment] 2023-10-05 04:00
> hehe

The text on page 20 is clearer.

**Comment by nicowilliams** [comment] 2023-10-05 04:02
Page 24 in the online copy you linked.

**Comment by nicowilliams** [comment] 2023-10-05 04:02
So, you can `break`, and you can `error` your way out.  I.e., no change is needed, if we want to keep it consistent with Icon's `repeat`.

**Comment by emanuele6** [comment] 2023-10-05 04:11
Yes, I saw that example, and there `repeat` stops because the body runs `break`, not because the body does not return anything.

Also in the many code examples on the website of the University of Arizona, `repeat case Event() of` stops beacuse if `Event()` returns `"q"`, the `case` expression runs `break`, not because `Event()` returns nothing.

So it seems to work like ICON's repeat already. It could be that OP is saying that if `expr` throws an error, `repeat` should stop, and `empty` should be treated as an error, and I am just not realising it because I don't know ICON so I don't know how much it has in common with `jq`. (errors? functions that possibly return nothing? functions that return multiple values?)

**Comment by nicowilliams** [comment] 2023-10-05 04:26
> So it seems to work like ICON's repeat already. It could be that OP is saying that if `expr` throws an error, `repeat` should stop, and `empty` should be treated as an error, and I am just not realising it because I don't know ICON so I don't know how much it has in common with `jq`. (errors? functions that possibly return nothing? functions that return multiple values?)

In Icon failure (jq's `empty`) is treated as falsity, not as an error.  Errors in Icon can be either terminate the program if `&error` is zero or turn into failure depending on otherwise (and then `&error` is decremented).  There's other `&things` that record error information.  So you can "catch" errors by turning them into failures (by setting `&error` to a non-zero value) then check `&errortext` and `&errorvalue`, then call `errorclear()` to clear the error -- it's very non-ergonomic to catch errors.  You can raise an error with `runerr()`.

I never tested it, and I don't have Icon installed, but I believe that errors inside `repeat` can be caught outside it.

jq and Icon are remarkably similar.  @stedolan has told me he never knew about Icon.

**Comment by nicowilliams** [comment] 2023-10-05 04:27
Now, `repeat` will be more useful when we add more I/O functionality, just as in your example regarding event handling in Icon.

**Comment by nicowilliams** [comment] 2023-10-05 04:28
I think we can close this now.

**Closed by nicowilliams** 2023-10-05 04:28 UTC
Labels: feature request
