### ISSUE TITLE
Shorthand for `.. | .IDENT? // empty` wanted

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#1568] opened 2018-01-03 04:55 UTC
Currently if you want to do this, you can use something like this:

~~~sh
jq '.. | .permalink? | . // empty' search.json
jq '.. | .permalink? | select(.)' search.json
jq '.. | .permalink? | values' search.json
jq 'recurse | .permalink? | . // empty' search.json
jq 'recurse | .permalink? | select(.)' search.json
jq 'recurse | .permalink? | values' search.json
~~~

However I am not happy with these invocations. In all cases, the third step is
needed because the second step generates extraneous `null`s. I feel this second
step is the root of the problem. Looking at `?`:

> Error Suppresion / Optional Operator: ?
>
> The ? operator, used as EXP?, is shorthand for try EXP.

so essentially with the command above we are knowingly creating errors, then
silencing them with `?`. This feels wrong. Can the second step be run in such a
way as to not generate an error? Or perhaps a `recurse(f)` or
`recurse(f; condition)` call would solve this?

**Comment by svnpenn** [comment] 2018-01-03 05:00
https://github.com/stedolan/jq/issues/536

**Comment by pkoppstein** [comment] 2018-01-03 05:07
> jq '.. | .permalink? | . // empty'

If you want to avoid "?" you could simply test to see whether the item is an object with the key, e.g.

.. | objects | select(has("permalink")) | .permalink

Note that the semantics of these two is not identical.  Consider for example if the input is `{"permalink":  null}`.

**Comment by svnpenn** [comment] 2018-01-03 05:35
https://github.com/stedolan/jq/issues/319

**Comment by svnpenn** [comment] 2018-01-03 05:38
@pkoppstein it seems like this should work too - but maybe I have wrong syntax:

~~~
$ jq 'recurse(.; has("permalink")) | .permalink' search.json
null
~~~

**Comment by nicowilliams** [comment] 2018-01-03 16:21
Maybe we could add a `... IDENT` / `...[STRING-VALUE]` form that effectively means `.. | .IDENT? // empty`.

**Comment by svnpenn** [comment] 2018-01-03 19:28
@nicowilliams nice - i didnt think about that:

~~~sh
jq '.. | .permalink? // empty' search.json
~~~

still not idea - but little better - thanks

**Comment by nicowilliams** [comment] 2018-01-03 20:44
@svnpenn I mean, I write that all the time, and it doesn't bother me enough to do something to shorten the idiom (and I added the `?` operator :)).  But I think adding `...IDENT` is worth thinking about.

**Comment by svnpenn** [comment] 2018-01-03 21:03
agree - current syntax is short enough - but the triple dot would be much easier to remember

**Comment by emanuele6** [comment] 2023-10-04 18:17
duplicate of #859

**Closed by emanuele6** 2023-10-04 18:17 UTC
Labels: feature request

**Comment by emanuele6** [comment] 2023-10-04 18:20
Kind of. Assuming the OP (who deleted their github account) meant shorthand for `select(has("IDENT")?).IDENT` instead of `.IDENT? // empty`, or `.IDENT? | values`.
