### ISSUE TITLE
jq should detect when stdout is closed (if it's a pipe or socket) and exit

### ISSUE THREAD

**Issue by ghost** [jqlang/jq#1285] opened 2016-12-03 02:51 UTC
Running:

~~~
jq | head
~~~

hangs on master. 5fe053671a768d28bc9773719cc4a9a35e72f30d is the culprit. Here
is Git bisect:

~~~
5fe053671a768d28bc9773719cc4a9a35e72f30d is the first bad commit
commit 5fe053671a768d28bc9773719cc4a9a35e72f30d
Author: Nicolas Williams <nico@cryptonector.com>
Date:   Tue Dec 1 22:16:03 2015 -0600

    Assume . if either stdin/on isatty() (fix #1028)

    And move the #define of isatty on Windows up.
~~~

**Comment by svnpenn** [comment] 2016-12-03 02:55
https://github.com/stedolan/jq/issues/1028

**Comment by svnpenn** [comment] 2016-12-03 03:00
Looks like workaround is:

~~~
jq -h | head
~~~

but this is not intuitive

**Comment by nicowilliams** [comment] 2017-01-23 18:21
*sigh*

**Comment by svnpenn** [comment] 2017-01-23 19:34
@nicowilliams development seems to have stalled? Would you be interested to add me as collaborator?

**Comment by nicowilliams** [comment] 2017-01-23 21:56
@svnpenn We certainly need more developers, yes.  What I'd like to do is review PRs and then upgrade authors to collaborator status as they need less and less hand-holding.  Send me a PR!

**Comment by svnpenn** [comment] 2017-01-23 22:05
Hm, no thanks. I have made commits to this repo already, so I had hoped I had already proven myself.

**Comment by nicowilliams** [comment] 2017-01-24 06:01
@svnpenn I can't hand out committer access.  I can only recommend new prospective committers to @stedolan.  There are two small commits from you in the repo (and maybe neglected PRs? let me know) -- nothing wrong with that, but maybe @stedolan would like to see more?  I wouldn't mind, and he's hard to get a hold of, so a bit more from you would help.  Besides, it's just access to push, not access to author.  You can author any time you like and get me (or @wtlangford) to pull your commits.  If we're unresponsive to issues, there's always e-mail.

**Comment by itchyny** [comment] 2023-06-03 01:58
This does not look like a bug. The command just waits for standard input. Waiting for comments from other maintainers.

**Comment by nicowilliams** [comment] 2023-07-07 16:22
@itchyny I agree it's not a bug.  I suppose we might could do something about this though trying to detect error conditions on `STDOUT_FILENO` when it's a pipe or a socket.

**Comment by nicowilliams** [comment] 2023-07-07 16:24
https://unix.stackexchange.com/a/736795
https://unix.stackexchange.com/a/736865

Basically, this is a common problem.  We could:

 - early in `main()` check if `STDOUT_FILENO` is a pipe or socket
 - if it is a pipe/socket, then at every input check if `STDOUT_FILENO` is closed by using `poll()` with `POLLERR` and zero timeout
 - if we detect that it's closed then exit

None of this will help with getting `jq` to exit when it's taking a long time to compute an output.  For that we'd need a thread to check for the pipe/socket being closed then set a global that we can poll in the VM, in `jq_next()` every so many opcodes -- I'm not keen on that.

So maybe we could re-open this and make it a feature request since there are Unix commands that do this.

**Comment by emanuele6** [comment] 2023-07-07 16:52
I don't understand what the issue is. `jq` is just reading stdin, and outputting the input as pretty formatted JSON, and `head` will limit that output to the first 10 lines.

If you press `^D` on your terminal, `jq` will notice there is no input to read, and exit, and then `head` will exit too because the write end of the pipe held by `jq` has closed.

stdout is not closed there, nor is the read of the pipe, `head` is still alive.

If you dump a JSON value that pretty formatted is larger than `jq`'s output buffer, and spans at least 10 lines, `jq` will print that value, `head` will exit after printing the first 10 lines, and then `jq` will die the next time it writes to it:
```
$ jq | head
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]<enter>
[
  [
    [
      [
        [
          [
            [
              [
                [
                  [
$
```

The confusing thing is that when `stdout` is a terminal, `jq` with no arguments behaves like `jq -h`; while it normally behaves like `jq .` if stdout is something else.

**Comment by nicowilliams** [comment] 2023-07-07 18:11
@emanuele6 the issue is that the jq program and its future input are such that the jq program will never output again and also will not terminate, but the program on the other side of `jq`'s `stdout` pipe may have exited, and so it would be nice if `jq` would also exit _as if it had tried to write and gotten `EPIPE`/`SIGPIPE`_.  The only way to do that would be to asynchronously or periodically check that the `stdout` pipe is still there and have `jq` exit when the other side of the pipe gets closed.

**Comment by emanuele6** [comment] 2023-07-07 18:18
So we are talking about handling something like `jq | true`, not `jq | head` like in the original post?

But I don't understand why `jq` should handle this, it is just waiting for input on the stdin terminal that is able to provide data; if you press `^D` in the terminal, some invalid JSON that will trigger a fatal input error, or enter the input from before that generates a large enough output to fill the output buffer, `jq | true` and `jq >&-` will terminate too. 

```
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
```

`jq` is just waiting for input, from a source of input that is able to send input, it is not hanging forever

**Comment by nicowilliams** [comment] 2023-07-07 18:52
> So we are talking about handling something like `jq | true`, not `jq | head` like in the original post?

`while true; do echo 1; done | jq empty | true` is the perfect reproducer, yes.  Here `jq` is constantly finding inputs to process, never outputting anything, and also never finding out that it should exit because the command to the right of it in the pipeline has exited.

> But I don't understand why `jq` should handle this, it is just waiting for input on the stdin terminal that is able to provide data; if you press `^D` in the terminal, some invalid JSON that will trigger a fatal input error, or enter the input from before that generates a large enough output to fill the output buffer, `jq | true` and `jq >&-` will terminate too.

Except in OP's example `jq` _is reading plenty of inputs_, and if you search you'll find posts like [[Why isn't `tail -f … | grep -q …` quitting when it finds a match?](https://superuser.com/questions/1404982/why-isnt-tail-f-grep-q-quitting-when-it-finds-a-match)](https://superuser.com/questions/1404982/why-isnt-tail-f-grep-q-quitting-when-it-finds-a-match) where this turns out to be a fairly obscure but very generic issue that does occasionally affect users.  (Alright, that post is not a great analog for this issue here, but if you squint it looks similar enough.  I found that via https://unix.stackexchange.com/questions/732503/how-to-find-out-if-pipe-is-broken/736795#736795 which is a lot more interesting.)

I don't consider this quite a bug in `jq`, but more like a design bug in the Unix shells.  What should probably happen is that when the right-most command in the pipeline exits then the rest should get a signal -- historically that signal is `SIGPIPE` as those other commands attempt to write to `stdout`, and that has generally been good enough except in corner cases like this one.  Perhaps the _shell_ should send `SIGPIPE` to the other commands when the right-most one exits, possibly after some time.  But it's just easier to work around this in commands like `jq` and `tail` and `grep` than it is to work around it in the shells (even just bash), and it's also more correct since each such program can exit cleanly at an appropriate time and then we don't have to think about having a timer before sending `SIGPIPE` from the shell.

**Comment by emanuele6** [comment] 2023-07-07 18:55
@nicowilliams I think this report was confused; the original report was that `jq | anyprogramwhatever` hangs because `jq` without arguments acts as `jq .`, so it is reading JSON input and outputting it formatted to stdout.

But `jq` without arguments in a terminal behaves like `jq -h`, so OP thought `jq | head` should have worked like `jq -h | head` and exit immediately, because `jq -h` print its help, and exits immediately. (probably they tried to run `jq | head` to read `jq`'s help message more easily since it is long.)

Maybe this behaviour should be removed, and `jq` without arguments should always behave like `jq .` to avoid confusions, and require that the user uses `-h`/`--help` to see the help message; I personally also find that `jq` in a terminal works like `jq -h` confusing.

---

What this issue has transformed into, as far as I understand, is the folllowing:

```
$ jq -c --unbuffered | head -n 3
1
1
[
  "hi",
  "hello",
  "foo"
]
["hi","hello","foo"]
  {    }
{}
<head has exited, but jq will still wants to read the next input, and it will only die once it tries to write something to the stdout>
```

And you want `jq` to detect that stdout is a pipe write end which cannot accept output, and it should not try to handle more input.
I don't think that should happen; plus, if you don't use `--unbuffered`, this won't even be effective because `jq` won't have generated enough output, so it won't write anything and wait for more things to read, and `head` won't exita and close the read end of the pipe.

Personally, I think it would be weird to see `jq` perform this magic in my opinion, but we can discuss it if you want to have this feature, maybe we should use a new issue though.

---
NOTE: I was writing this comment while you sent the comment before this one, so I have not read it yet.

**Comment by nicowilliams** [comment] 2023-07-07 18:56
> it is not hanging forever

Indeed, it's not.  The user, however, can't figure that out -- from their perspective it's "hanging".

**Comment by nicowilliams** [comment] 2023-07-07 18:59
> @nicowilliams I think this report was confused; the original report was that `jq | anyprogramwhatever` hangs because `jq` without arguments acts as `jq .`, so it is reading JSON input and outputting it formatted to stdout.

Oh, maybe I re-titled and commented on the wrong issue!  _sigh_

There was an issue where the issue was as I describe above.

**Comment by nicowilliams** [comment] 2023-07-07 18:59
I'm closing this and if I find the other issue I'll comment on it.

**Closed by nicowilliams** 2023-07-07 18:59 UTC
Labels: feature request, support, not a bug

**Comment by nicowilliams** [comment] 2023-07-07 19:14
@emanuele6 argh, it was #1691 that I'd meant to leave these comments in.  Wrong browser tab...
