### ISSUE TITLE
fromdate produces an Epoch timestamp that is one hour off

### ISSUE THREAD

**Issue by sgp** [jqlang/jq#2490] opened 2022-10-12 14:22 UTC
**Describe the bug**

Parsing an ISO8601 timestamp yields a timestamp that is off by 3600 seconds.

**To Reproduce**

```
echo 1665511200 | jq todate | jq fromdate
1665514800
```

**Expected behavior**

Expected the round trip from `todate` (which produces an ISO8601) to `fromdate` would yield the same result.

**Environment (please complete the following information):**
 - OS and Version: macOS Monterey 12.6, also reproduced on Linux (Fedora 34)
 - jq version 1.6

**Additional context**

🤷

**Comment by mkj-pendo** [comment] 2022-10-12 14:31
This is possibly related to DST.

On Fedora 36, jq 1.6:

```bash
$ date
Wed Oct 12 10:30:23 AM EDT 2022
$ echo 1665511200 | jq todate | jq fromdate
1665514800
$ export TZ=UTC
$ date
Wed Oct 12 02:31:08 PM UTC 2022
$ echo 1665511200 | jq todate | jq fromdate
1665511200
```

**Comment by sgp** [comment] 2022-10-12 14:31
This is definitely `mktime`'s fault, as `fromdate` is just an alias for `strptime("%Y-%m-%dT%H:%M:%SZ")|mktime`.

```
echo 1665511200 | jq -c 'todate|strptime("%Y-%m-%dT%H:%M:%SZ")'
[2022,9,11,18,0,0,2,283]

echo "[2022,9,11,18,0,0,2,283]" | jq mktime
1665514800

**Comment by sgp** [comment] 2022-10-12 14:33
@mkj-pendo that checks out, as the code for `mktime` ... is [messy](https://github.com/stedolan/jq/blob/master/src/builtin.c#L1266-L1308).

**Comment by eternaleye** [comment] 2022-12-08 21:54
It might be advisable to use `timegm` when available. It's not POSIX, but it's a GNU extension also supported by the BSDs, musl, bionic libc, and macOS. On Windows, there is [`_mkgmtime`](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/mkgmtime-mkgmtime32-mkgmtime64?view=msvc-170).

**Comment by jmoldow** [comment] 2024-07-09 01:51
I believe this is a duplicate of #2001 and can probably be closed, since it is fixed in jq 1.7 (though that version still isn't released to Debian and probably other systems as well).

**Comment by wader** [comment] 2024-07-09 10:01
@jmoldow thanks for researching. @sgp are you able to reproduce with 1.7?

**Comment by sgp** [comment] 2024-07-12 18:51
Tried this on `jq 1.7.1`, and it looks good

```
❯ echo "[2022,9,11,18,0,0,2,283]" | jq mktime
1665511200
❯ echo 1665511200 | jq -c 'todate|strptime("%Y-%m-%dT%H:%M:%SZ")'
[2022,9,11,18,0,0,2,283]
❯ echo 1665511200 | jq todate | jq fromdate

1665511200
```

**Closed** 2024-07-12 18:52 UTC
Labels: bug, datetime
