### ISSUE TITLE
Try/catch doesn't work with field updates

### ISSUE THREAD

**Issue by burtgulash** [jqlang/jq#2230] opened 2020-12-17 15:17 UTC
**Describe the bug**
try/catch doesn't seem to be working well with field updates.

**To Reproduce**
% echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}
% echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":"error"}

**Environment (please complete the following information):**
% jq --version
jq-1.6

**Comment by odnoletkov** [comment] 2020-12-17 17:37
Seems like a duplicate of #2220 and #2140

**Comment by itchyny** [comment] 2020-12-18 08:14
And this is already fixed in the master version.
```sh
 % jq --version
jq-master-a17dd32

 % echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}

 % echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":123}
```

**Comment by emanuele6** [comment] 2023-09-08 20:15
jq 1.7 released with the fix.
```bash
$ jq --version
jq-1.7
$ echo '{"x":"123"}' | jq -c '.x = (.x | try tonumber catch "error")'
{"x":123}
$ echo '{"x":"123"}' | jq -c '.x |= (try tonumber catch "error")'
{"x":123}
```
closing

**Closed by emanuele6** 2023-09-08 20:15 UTC
Labels: bug, dup, fixed in master
