### ISSUE TITLE
inside function is broken

### ISSUE THREAD

**Issue by vrkiran** [jqlang/jq#1896] opened 2019-04-26 17:47 UTC
Works correctly
```
$ echo '{"a":"1"}' | jq -c '[.a] | inside(["1", "2"])'
true
```

**Wrong result. This is expected to return false.**
```
$ echo '{"a":"1"}' | jq -c '[.a] | inside(["101", "2"])'
true
```

**Comment by pkoppstein** [comment] 2019-04-26 18:35
@vrkian - `inside` is defined in terms of `contains`, which has very unusual (surprising to many) semantics.

Consider for example:

    $ jq -n '["123"] | contains(["1"])'
    true

This is the intended behavior, and is in accordance with the documentation.

So you might not be alone in concluding that `contains` and `includes` are not worth the trouble.

**Comment by vrkiran** [comment] 2019-05-19 18:04
@pkoppstein Thanks for the reply. Is there a better alternative in jq for this, other than a long list of == and or statements?

**Comment by pkoppstein** [comment] 2019-05-19 18:26
If your jq has `IN` (uppercase), then you could use that, e.g.:

```
echo '{"a":"1"}' | jq '.a | IN("101", "2")'
false

echo '{"a":"1"}' | jq '.a | IN("1", "2")'
true
```

If your jq does not have `IN`, you could include a suitable `def`, e.g.

    def IN(s): first((s == .) // empty) // false;

Or use the built-in function `index` (lowercase).

**Comment by vrkiran** [comment] 2019-05-21 16:09
@pkoppstein What do you mean by having IN in my jq? Is it some sort of plugin I need to install? Or a specific version of jq? I believe I have the latest version installed, but I can always upgrade.

**Comment by pkoppstein** [comment] 2019-05-21 16:47
Different versions of jq have different sets of "builtin" functions.  Some such functions are (purposefully) not documented in the official documentation, so it's worth knowing that a builtin function named "builtins" was added a while ago.  

If your jq has the "builtins" builtin, you can use it to check for the presence of any builtin by running something like this:

     jq -n builtins | grep -w FOO

where FOO is the relevant function name.  Using jq 1.6:

    $ jq -n builtins | grep built
    "builtins/0"

If your jq does not have `builtins/0`, you can check whether a particular function with a particular arity is built-in by checking if its invocation produces an error message, e.g.

   $ jq-1.5 -n 'IN(null;null)'
    jq: error: IN/2 is not defined at <top-level>, line 1:

Or check the relevant builtins.jq file -- e.g. by googling for: jq builtins.jq

**Comment by itchyny** [comment] 2023-06-03 05:22
As explained above, this is working as intended, so closing the issue.

**Closed by itchyny** 2023-06-03 05:22 UTC
Labels: support
