### ISSUE TITLE
tonumber with math, unexpected trailing trash results

### ISSUE THREAD

**Issue by d51r3verse** [jqlang/jq#2389] opened 2021-12-24 11:14 UTC
**Describe the bug**
`tonumber` single use result was as expected.
But with math like `|tonumber*100.0`, it will **randomly** adds trailing useless numbers(maximum 13 digits after decimal point).

**To Reproduce**
```
20211224.10:56:54 root@abn:~/lepup# echo \"34.567890\" | jq '.|tonumber'
34.56789
20211224.10:57:03 root@abn:~/lepup# echo \"34.567\" | jq '.|tonumber'
34.567
20211224.10:57:09 root@abn:~/lepup# echo \"34.567890\" | jq '.|tonumber*100.0'
3456.7889999999998
20211224.10:57:27 root@abn:~/lepup# echo \"34.567\" | jq '.|tonumber*100.0'
3456.7
20211224.10:57:39 root@abn:~/lepup# echo \"0.0579\" | jq '.|=tonumber*100.0'
5.79

```

**Expected behavior**
```
# echo \"34.567890\" | jq '.|tonumber*100.0'
3456.789
```

**Environment (please complete the following information):**
`Linux armbian 5.10.60-rockchip64 #21.08.1 SMP PREEMPT Wed Aug 25 18:56:55 UTC 2021 aarch64 GNU/Linux`
`jq-1.5-1-a5b5cbe`
and
`Windows 10 20H2 + jq-win64.exe(v1.6)`

**Additional context**
Any alternative(currently maintained) jq available?
or, anyone advice how transform `"0.0749"` to `7.49`?

**Comment by itchyny** [comment] 2021-12-28 05:58
This is caused by floating-point arithmetic and happens in other languages too (try `ruby -e 'p 34.567890 * 100.0'`). Since decimal floating-point (like `decimal` package in Python) is not supported, you need to transform by string operations, or wait for `(s)printf` to be implemented (see #614) to format numbers in fixed digits.

**Comment by d51r3verse** [comment] 2021-12-28 09:45
Thanks @itchyny 
Understood that this is known issue.

If anyone got this problem, My poor man style😝 workaround was add following sequence before jq
`| perl -pe 's/("[^:\[{"]*rate[^:\[{"]*"\s*:\s*)"(\d+\.?\d{1,4})\d*"/$1.($2*100)/gie'`

**Comment by itchyny** [comment] 2023-06-03 05:26
This is floating-point arithmetic behavior and not a bug, so closing.

**Closed by itchyny** 2023-06-03 05:26 UTC
Labels: support
