### ISSUE TITLE
Releasing 1.6 final?

### ISSUE THREAD

**Issue by jakirkham** [jqlang/jq#1689] opened 2018-07-20 01:47 UTC
Just raising this to get an idea of when 1.6 final might be released. Thanks for all of your work.

**Comment by bendem** [comment] 2018-07-20 08:23
duplicate of #1352

**Comment by itchyny** [comment] 2023-06-03 02:59
The release [1.6](https://github.com/jqlang/jq/releases/tag/jq-1.6) was made in Nov 2018, so closing this issue.

**Closed by itchyny** 2023-06-03 02:59 UTC
