### ISSUE TITLE
Add -0 command-line option

### ISSUE THREAD

**Issue by nicowilliams** [jqlang/jq#1373] opened 2017-03-27 16:59 UTC
It'd be nice to be able to use ASCII `NUL` instead of `LF` for non-raw-output mode for use with `xargs -0` and such.  In raw output mode, of course, one can use `-j` and output `"\u0000"` as necessary.

As a workaround until this is done, use raw-output mode and output raw values, but pipe all strings to `tojson` first: `jq -rj '... | if type=="string" then tojson else . end'`.

**Comment by bsolomon1124** [comment] 2020-06-12 19:07
Related to/dupe of https://github.com/stedolan/jq/issues/1658.

**Comment by itchyny** [comment] 2020-06-13 02:57
The `--nul-output` is already implemented by  #1990 (which closed #1271). `jq --nul-output '.. | tojson'` does the trick.

**Comment by bsolomon1124** [comment] 2020-06-16 14:09
Thanks @itchyny, though it looks like that option does not exist on `jq-master-v20200428-28-g864c859e9d`, which is the version available on Alpine 3.12.0.

**Comment by bsolomon1124** [comment] 2020-06-16 14:14
Indeed, the last release of jq was in 2018, long before this option was added. Are the releases no longer being updated and should we just build from source instead?

**Comment by asottile** [comment] 2020-12-28 20:59
I just built this from source, it looks like `-0` is ignored (and also not part of the help text) -- `--nul-output` seems to work though 👍

**Comment by wader** [comment] 2023-07-07 10:22
@itchyny anything left to do for this issue?

**Comment by itchyny** [comment] 2023-07-08 00:05
This option has been fully implemented, so closing the issue.

**Closed by itchyny** 2023-07-08 00:05 UTC
Labels: feature request, fixed in master
