### ISSUE TITLE
version 1.6 tar compile fails on builtin oniguruma

### ISSUE THREAD

**Issue by terefang** [jqlang/jq#2372] opened 2021-11-15 10:40 UTC
i had to do the following to make it work

```
tar -xvf jq-1.6.tar.gz
cd jq-1.6
cd modules/oniguruma
autoreconf -fi
cd ../..
./configure --with-oniguruma=builtin
```

**Comment by nobodyinperson** [comment] 2021-11-18 06:55
`modules/oniguruma` is a git submodule. So when cloning the repository, `git clone --recursive https://github.com/stedolan/jq` is necessary to get that as well. Building then works after running `autoreconf -fi` in that submodule as you suggested. Thank you!

The [docs](https://stedolan.github.io/jq/download/) should reflect that.

**Comment by lightmare** [comment] 2022-03-31 12:57
@nobodyinperson docs won't fix this issue. It has nothing to do with oniguruma being a git submodule. The issue is not missing submodule sources. It is about the release source tarball, which does contain required sources under modules/oniguruma, but doesn't contain `modules/oniguruma/configure` script.

Because of that, the released sources cannot be built with just the usual `./configure && make`

For me the issue is that I'm trying to build from tarball specifically because I need to avoid having to run autoreconf, because where I'm building, autoreconf on jq fails because of too old autoconf, and autoreconf on oniguruma fails because of too old automake.

**Comment by itchyny** [comment] 2023-06-25 13:51
Same issue as #1872, we need to be careful in the next release.

**Closed** 2023-07-03 12:05 UTC
Labels: build
