### ISSUE TITLE
Serious sync issues

### ISSUE THREAD

**Issue by danimesq** [jqlang/jq#2344] opened 2021-08-30 02:09 UTC
Version: jq-1.6

These commands:

> echo '{"version": "v1"}' > /tmp/eventsheet.json
> 
> cat /tmp/eventsheet.json | jq --arg next_var "1" '. + {next_var: $next_var}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
> 
> cat /tmp/eventsheet.json | jq '. + {next_var: 1}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
> 
> cat /tmp/eventsheet.json | jq --arg vars "[]" '. + {vars: $vars}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
> 
> cat /tmp/eventsheet.json | jq '. + {vars: []}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json

Have resulted in this:

> {
>   "version": "v1",
>   "next_var": 1,
>   "vars": []
> }
> }

It have one more "}".

The commands are correct, but it seems that jq have sync issues when writing to json files (excellent at reading but not so at writing).

Its an Electron app, but I had similar write sync issues from this bash program: https://github.com/DaniellMesquita/Web3Updater

@stedolan

**Comment by DaniellMesquita** [comment] 2021-08-30 02:20
Typing every command on terminal, you won't perceive any problem.

But when leveraging JQ programatically, with succeeded events on an bash script or Electron app, this issue can be reproduced.

On Electron/NodeJS, to run an shell command:

> const{exec}=require('child_process');exec(`YOUR_COMMAND_HERE`,(error,stdout,stderr)=>{if(error){console.log(`error:${error.message}`);return}if(stderr){console.log(`stderr:${stderr}`);return}console.log(`${stdout}`)});

But this could be reproduced in an bash script as well, as its happening on Web3Updater, linked in the previous comment.

**Comment by vintnes** [comment] 2021-08-30 04:19
Unable to replicate interactively or programmatically.
Please close this issue; we can't provide JS support here.

```
$ declare -p BASH_VERSION
declare -- BASH_VERSION="5.1.4(1)-release"

$ alias jq=/usr/bin/jq

$ jq --version
1.6

$ cat 2344.bash
echo '{"version": "v1"}' > /tmp/eventsheet.json
cat /tmp/eventsheet.json | jq --arg next_var "1" '. + {next_var: $next_var}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
cat /tmp/eventsheet.json | jq '. + {next_var: 1}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
cat /tmp/eventsheet.json | jq --arg vars "[]" '. + {vars: $vars}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json
cat /tmp/eventsheet.json | jq '. + {vars: []}' > /tmp/eventsheet.json2 && mv -f /tmp/eventsheet.json2 /tmp/eventsheet.json

$ bash 2344.bash && cat /tmp/eventsheet.json
{
  "version": "v1",
  "next_var": 1,
  "vars": []
}
```

**Comment by DaniellMesquita** [comment] 2021-09-01 02:10
> Please close this issue; we can't provide JS support here.

I'm not using an JS version of jq, but the official binary jq 1.6; one app is leveraging jq through bash, and other through JS; but still the official JQ.

Here is the Electron app, that can be tested with `npm start`:
https://drive.google.com/file/d/1U1YnhnK-QuzXpzpccJuH45kElTYCw1vN/view?usp=sharing
![Screenshot_20210830_233713](https://user-images.githubusercontent.com/6765277/131432728-389e4e35-69e2-492c-9f1d-7bc4ae904239.png)

**Comment by Maxdamantus** [comment] 2021-09-03 09:22
Hard to comment on what that app is doing. I don't want to run it, but I imagine if you're seeing that behaviour, it probably means it's running the same pipeline multiple times concurrently:
* One instance of `jq '...' >/tmp/eventsheet2.json` starts, writes all but the last '}' character
* Another instance of `jq '...' >/tmp/eventsheet2.json` starts and runs to completion; in doing so, `/tmp/eventsheet2.json` was truncated at the beginning (due to use of `>` in the shell)
* The first `jq` instance continues, appending the last '}' character that it had not yet written, after the output of the second `jq` instance

If you want to make your command concurrency safe, you should do something like:
```tmp="$(mktemp)"; cat /tmp/eventsheet.json | jq '...' >"$tmp" && mv "$tmp" /tmp/eventsheet.json```

Alternatively, the `sponge` command from moreutils was designed for this sort of thing (though unlike `mktemp`, it's not normally part of a standard OS installation):
```cat /tmp/eventsheet.json | jq '...' | sponge /tmp/eventsheet.json```

**Comment by itchyny** [comment] 2023-06-05 23:50
Closing the issue as detailed workarounds are commented above. I don't think this is a jq issue.

**Closed by itchyny** 2023-06-05 23:50 UTC
Labels: support
