### ISSUE TITLE
jq stuck on stdin EOF when in the chain of shell pipe

### ISSUE THREAD

**Issue by jschwinger233** [jqlang/jq#3224] opened 2024-12-20 09:30 UTC
**Describe the bug**

If jq runs in the middle of shell pipeline like `a | jq | b`, jq can only write at maximum 4096 bytes to process `b` before process `a` exits.

**To Reproduce**

1. Prepare a big json larger then 4096 bytes, like:

```
{"apiVersion":"v1","kind":"Pod","metadata":{"creationTimestamp":"2024-12-20T09:01:03Z","generateName":"test-conn-disrupt-server-cfd89b85b-","labels":{"app":"test-conn-disrupt-server","kind":"test-conn-disrupt","name":"test-conn-disrupt-server","pod-template-hash":"cfd89b85b"},"name":"test-conn-disrupt-server-cfd89b85b-pwksc","namespace":"cilium-test-1","ownerReferences":[{"apiVersion":"apps/v1","blockOwnerDeletion":true,"controller":true,"kind":"ReplicaSet","name":"test-conn-disrupt-server-cfd89b85b","uid":"7d2cb475-52c2-495b-95c3-c8d704d4296b"}],"resourceVersion":"77182","uid":"47f169bb-b96e-4ae6-b075-6adacd80f51a"},"spec":{"containers":[{"command":["tcd-server","8000"],"env":[{"name":"PORT","value":"8000"},{"name":"NAMED_PORT","value":"port-8000"}],"image":"quay.io/cilium/test-connection-disruption:v0.0.14@sha256:c3fd56e326ae16f6cb63dbb2e26b4e47ec07a123040623e11399a7fe1196baa0","imagePullPolicy":"IfNotPresent","name":"test-conn-disrupt-server","ports":[{"containerPort":8000,"name":"port-8000","protocol":"TCP"}],"readinessProbe":{"exec":{"command":["cat","/tmp/server-ready"]},"failureThreshold":20,"initialDelaySeconds":1,"periodSeconds":3,"successThreshold":1,"timeoutSeconds":1},"resources":{"requests":{"cpu":"100m"}},"securityContext":{"capabilities":{"add":["NET_RAW"]}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/run/secrets/kubernetes.io/serviceaccount","name":"kube-api-access-jn775","readOnly":true}]}],"dnsPolicy":"ClusterFirst","enableServiceLinks":true,"nodeName":"kind-worker2","preemptionPolicy":"PreemptLowerPriority","priority":0,"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"test-conn-disrupt-server","serviceAccountName":"test-conn-disrupt-server","terminationGracePeriodSeconds":30,"tolerations":[{"effect":"NoExecute","key":"node.kubernetes.io/not-ready","operator":"Exists","tolerationSeconds":300},{"effect":"NoExecute","key":"node.kubernetes.io/unreachable","operator":"Exists","tolerationSeconds":300}],"volumes":[{"name":"kube-api-access-jn775","projected":{"defaultMode":420,"sources":[{"serviceAccountToken":{"expirationSeconds":3607,"path":"token"}},{"configMap":{"items":[{"key":"ca.crt","path":"ca.crt"}],"name":"kube-root-ca.crt"}},{"downwardAPI":{"items":[{"fieldRef":{"apiVersion":"v1","fieldPath":"metadata.namespace"},"path":"namespace"}]}}]}}]},"status":{"conditions":[{"lastProbeTime":null,"lastTransitionTime":"2024-12-20T09:01:04Z","status":"True","type":"PodReadyToStartContainers"},{"lastProbeTime":null,"lastTransitionTime":"2024-12-20T09:01:03Z","status":"True","type":"Initialized"},{"lastProbeTime":null,"lastTransitionTime":"2024-12-20T09:01:05Z","status":"True","type":"Ready"},{"lastProbeTime":null,"lastTransitionTime":"2024-12-20T09:01:05Z","status":"True","type":"ContainersReady"},{"lastProbeTime":null,"lastTransitionTime":"2024-12-20T09:01:03Z","status":"True","type":"PodScheduled"}],"containerStatuses":[{"containerID":"containerd://6a8b7d7369a3255645b29d731c28a91076dab352cbb913610d12c1efe5fd09c2","image":"sha256:7eb91eaf1fef44a5701a171d295662598f4c0f934a6011497ef404a1eac8e2be","imageID":"quay.io/cilium/test-connection-disruption@sha256:c3fd56e326ae16f6cb63dbb2e26b4e47ec07a123040623e11399a7fe1196baa0","lastState":{},"name":"test-conn-disrupt-server","ready":true,"restartCount":0,"started":true,"state":{"running":{"startedAt":"2024-12-20T09:01:04Z"}}}],"hostIP":"172.20.0.5","hostIPs":[{"ip":"172.20.0.5"},{"ip":"fc00:c111::5"}],"phase":"Running","podIP":"10.244.3.44","podIPs":[{"ip":"10.244.3.44"},{"ip":"fd00:10:244:3::bb29"}],"qosClass":"Burstable","startTime":"2024-12-20T09:01:03Z"}}
```

Write this json in the `big.json`

2. Run cmd ` (cat /tmp/big.json && sleep 10) | jq '.' | grep 10.244.3.44`, we'll notice the grep doesn't output until 10s sleeping completes.

**Expected behavior**

The expected behavior is to see grep output immediately.

**Environment (please complete the following information):**

- OS and Version: Linux 6.8.0-49-generic 49~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov  6 17:42:15 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- jq version: jq-1.7.1

**Additional context**

I ran strace to diagnose the issue:

```
# (cat /tmp/big.json && sleep 2) | strace -fTtt -- jq '.' 2>/tmp/jq.strace | grep 10.244.3.44

...
17:27:03.678722 write(1, "{\n  \"apiVersion\": \"v1\",\n  \"kind\""..., 4096) = 4096 <0.002055>
17:27:03.681125 read(0, "", 4096)       = 0 <1.977842>
17:27:05.659149 write(1, "\n      }\n    ]\n  },\n  \"status\": "..., 1889) = 1889 <0.000142>
17:27:05.659460 close(1)                = 0 <0.000037>
17:27:05.659713 exit_group(0)           = ?
17:27:05.660325 +++ exited with 0 +++
```

strace clearly showed jq (unnecessarily?) waited for EOF from fd=0(stdin) before continued to write remaining bytes to fd=1(stdout).

**Comment by wader** [comment] 2024-12-20 09:40
I think this might be due to buffering, but not exactly sure what is going. With `jq --unbuffered` it seems to work as intended.

**Comment by jschwinger233** [comment] 2024-12-20 09:45
Thank you Mattias, do you think this is an issue worth keeping open, or we can close as this is expected.

**Comment by georgalis** [comment] 2024-12-20 09:54
@wader Yeah, that makes sense, the fd doesn't close until the (subshell) exits, jq is probably waiting for the next chunk *from the subshell* which stays open until sleep is done. this would probably take 2 sec  (cat /tmp/big.json && sleep 2 && cat /tmp/big.json) | jq . | grep 10.244.3.44

you will have much better performance with `grep 10.244.3.44 < <(jq . < <(cat /tmp/big.json))` this is called Process Substitution in man bash, and doesn't spawn a new shell for each pipe and the () it's a single thread approach.

**Comment by georgalis** [comment] 2024-12-20 10:02
even if you did `{cat /tmp/big.json && sleep 2 ;} | yq . | grep 192.168` you would get the delay because the first pipe doesn't know when the end of the data comes, only the end of the expression.

**Comment by georgalis** [comment] 2024-12-22 00:32
> Thank you Mattias, do you think this is an issue worth keeping open, or we can close as this is expected.

@jschwinger233 you can probably just close it. this is normal behavior for programs that handle stdin, like sed awk and grep. this is from the grep man

```
--line-buffered
             Force output to be line buffered.  By default, output is line buffered when standard output is a terminal and block buffered otherwise.
```

it's a performance thing, much more efficient to process an entire block (typically 512 bytes) or line verses processing the input at each character, in some cases that means you won't see data that hasn't filled up the buffer. For example if you `tail -f access_log | grep {your query} | grep {your ip}` and then query the webserver, you may not see the log until further entries fill up the grep buffer.

**Closed as completed** 2024-12-22 03:22 UTC
