### ISSUE TITLE
object ({"last"...) cannot be csv-formatted, only array

### ISSUE THREAD

**Issue by Safinok** [jqlang/jq#2181] opened 2020-09-03 19:49 UTC
When I try on jqplay.org working fine, but when I try in command line Ubuntu 20.04 gives me always: object ({"last"...) cannot be csv-formatted, only array.

Itried in this way: jq -r '{ last } + (.onPlay[] | { category, age, score }) + (.response[] | { score }) | @csv' play.json 

JOSN file looks like that:
`{
    "onPlay": [
        {
            "category": "A",
            "age": 16,
            "score": 60
        },
        {
            "category": "B",
            "age": 17,
            "score": 80
        },
        {
            "category": "C",
            "age": 20,
            "score": 90
        }
    ],
    "lasat": 100,
    "response": [
        {
            "count": 4,
            "score": 100
        }
    ],
    "ed": 0,
    "v": "1.0"
}`

**Comment by pkoppstein** [comment] 2023-07-01 16:30
Closing this as `@csv` is in this case behaving as intended and as documented. The alleged anomalous behavior on jqplay is outside the scope of this forum. If the OP wishes to pursue the matter, stackoverflow.com would be a suitable forum.

**Closed by pkoppstein** 2023-07-01 16:30 UTC
Labels: support
