### ISSUE TITLE
Memory leak in function gen_cbinding

### ISSUE THREAD

**Issue by Hripsime-H** [jqlang/jq#2870] opened 2023-09-01 10:51 UTC
hi,
Memory leak in function gen_cbinding.
The memory leak is reported by a static analyzer tool developed at CAST (https://www.linkedin.com/company/cast-center).

Specifically, dynamic memory is allocated [here](https://github.com/jqlang/jq/blob/df95871dd7415627bda6d70ce0569d0a4fbc22c6/src/compile.c#L1092) depend on `code`, `BLOCK` macro can assert [here](https://github.com/jqlang/jq/blob/df95871dd7415627bda6d70ce0569d0a4fbc22c6/src/compile.c#L244) if `code.first->prev` is not NULL and allocated memory remains not freed

**Comment by nicowilliams** [comment] 2023-09-05 14:59
Hi, thanks for the report, but this is not a leak.  The assertion is specifically meant not to trip, therefore we expect never to exit w/o freeing this allocation.  Now, of course we could have a bug creep in in the usage of `gen_cbinding()` or other functions/macros that causes one or more of `inst_join()`'s assertions to trip, but that's why those assertions are there: to help find such bugs.  And if such a bug should creep in, then exiting w/o freeing some `inst` allocation is hardly a big deal -- the bug itself is a big deal.

> Specifically, dynamic memory is allocated [here](https://github.com/jqlang/jq/blob/df95871dd7415627bda6d70ce0569d0a4fbc22c6/src/compile.c#L1092) depend on code, BLOCK macro can assert [here](https://github.com/jqlang/jq/blob/df95871dd7415627bda6d70ce0569d0a4fbc22c6/src/compile.c#L244) if code.first->prev is not NULL and allocated memory remains not freed

But is there a code path that ever leads to `inst_join()` getting called with non-`NULL` `b->prev`?  We'd want to fix that immediately.

**Comment by emanuele6** [comment] 2023-10-08 14:23
Can't reproduce, closing for now

**Closed as completed by emanuele6** 2023-10-08 14:23 UTC
Labels: bug
