### ISSUE TITLE
Subtract operator

### ISSUE THREAD

**Issue by cleanthis** [jqlang/jq#1861] opened 2019-03-14 16:47 UTC
I am trying to subtract two numbers using the subtract operator:

{ "Test":(40.9 - 20.46) }

the result I get:

{ "Test": 20.439999999999998 }

Why? Is there a way to get the expected 20.44 value?

**Comment by nicowilliams** [comment] 2019-03-14 17:01
This is due to IEEE754 doubles being base-2.  The number formatter should be able to recognize this is 20.44 and print it as such, but evidently it didn't.

**Comment by muhmuhten** [comment] 2019-03-16 08:26
In this case, 40.9-20.46=0x1.470a3d70a3d70p4 while 20.44 is closest to 0x1.470a3d70a3d71p4, i.e. they differ in the LSD of the mantissa.

The classic example, of course, is

```
% jq -n 0.1+0.2
0.30000000000000004
```

**Comment by linquize** [comment] 2019-03-25 04:03
is there round function in jq?

**Comment by nicowilliams** [comment] 2019-03-25 04:15
@linquize yes, there is, and it's called round.  Most C math library functions are available in jq.

**Comment by itchyny** [comment] 2023-06-09 03:56
Closing the issue, as described above, this is caused by floating-point arithmetic and unlikely to be fixed (removed `fixed in master` which I mistakenly added by the confusion about the integer lossage issue).

**Closed by itchyny** 2023-06-09 03:56 UTC
Labels: ieee754
