### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ololoe** [jqlang/jq#1901] opened 2019-05-13 19:35 UTC
`jq . jq_crash.json > nul`

Segfault

jq_crash.json: `[]\x16` hex: 5b5d16

**Environment (please complete the following information):**
 - Windows XP
 - jq-1.6

**Comment by nicowilliams** [comment] 2019-05-13 21:11
I can't reproduce this using the jq version 1.6 win64 executable from the releases page on Windows 10.  I don't have Windows XP on hand to test with...

**Comment by bit2shift** [comment] 2019-05-28 19:17
Crash confirmed on Windows 7 x64 with jq 1.6 (`C:\msys2\mingw64\bin\jq.exe`).
But the crash is not caused by the file, but by the redirection.
<details>
<summary>Original file:</summary>
<img src="https://user-images.githubusercontent.com/6282023/58505376-b3940800-8184-11e9-87c9-92edfe16a340.png">
</details>
<details>
<summary>Syntactically correct file (without `\x16`):</summary>
<img src="https://user-images.githubusercontent.com/6282023/58505187-47b19f80-8184-11e9-901a-7b197c74feb0.png">
</details>

**Comment by ololoe** [comment] 2021-01-30 13:52
This seem to be fine on windows 10 64 bit. Would you fix it for older Windows versions, or 32 bit (don't know what's the cause of the bug)?

**Comment by itchyny** [comment] 2021-01-30 14:01
Possible related to #1180 and already fixed by 87594f81d6f63556f2644fff4ed493aaac97974c.

**Comment by ololoe** [comment] 2022-05-17 15:28
@itchyny This fix is from 2019, my bugreport is newer.

**Comment by ololoe** [comment] 2022-05-17 15:30
@itchyny In what version is it fixed?

**Comment by itchyny** [comment] 2023-09-08 21:27
1.7 is released.

**Closed by itchyny** 2023-09-08 21:27 UTC
Labels: fixed in master, windows
