### ISSUE TITLE
Default behaviour of objects and key sorting is dangerous and inconsistent

### ISSUE THREAD

**Issue by iFreilicht** [jqlang/jq#2568] opened 2023-04-06 15:16 UTC
**Describe the bug**
The default behaviour of `keys`, `keys_unsorted` and their (lack of) interaction with the `--sort-keys / -S` flag is dangerous.

By default, `keys` **does** sort the keys after extracting them, but regular objects are displayed and printed in insertion order. If you are unaware of this quirk, extracting keys from a json for conversion to tabular format will shuffle the column headers around, which can be very dangerous in financial contexts. `--sort-keys` will ensure that regular objects behave just like `keys` does, or one can use `keys_unsorted` to make keys follow the insertion order of the object attributes.

**To Reproduce**
```sh
$ echo -n '[{ "b": 2, "a": 1 }, {"b": 5, "a": 8}]' | jq -r "(.[0] | keys | @csv), (.[] | [.[]] | @csv)"
"a","b"
2,1
5,8
```

As you can see, the header is now in a different order than the columns, and the association between keys and values is broken. This might be noticeable in a situation where the values in the columns are very heterogeneous, but if that isn't the case, such a mistake can easily slip through.

**Expected behavior**
I would expect the output list of keys of the `keys` function to be in the same order as the attributes in the input object.

I would expect there to be three functions:
* `keys` follows the current global state of the `-S` flag. If it was not provided, the output list will be in insertion order. If it was provided, the output list will be ordered like the attributes of the input object
* `keys_unsorted` will always return the keys in attribute insertion order
* `keys_sorted` will always return the keys in sorted order

This would be a breaking change to the `keys` function, and I'm not entirely sure how to best handle that. Potentially, -S could be the default behaviour with an option to revert to unsorted behaviour, but this might impact performance.

**Environment (please complete the following information):**
 - OS and Version: macOS Ventura 13.3
 - jq version 1.6

**Comment by emanuele6** [comment] 2023-04-06 15:22
> * `keys` follows the current global state of the -S flag. If it was not provided, the output list will be in insertion order. If it was provided, the output list will be ordered like the attributes of the input object

This doesn't make sense since `-S` is an output option and it only affects the output when it is serialised back to JSON. It does not and it should not affect the evaluation of the `jq` script.

```bash
bash-5.1$ jq -cnS '{b:2,a:3} | keys_unsorted, .'
["b","a"]
{"a":3,"b":2}
```

**Comment by iFreilicht** [comment] 2023-04-06 21:29
Ahh ok, that's good to know. I actually didn't verify that `-S` solves this, I only tried `keys_unsorted` and that worked.

In that case I instead propose to only have one function that outputs the keys unsorted, and if you want them sorted you'd use `keys | sort`.

I suspect there was a very good reason not to do it like this in the first place, though. And even if there wasn't, a breaking change like this maybe shouldn't be released in a minor version.

**Comment by pkoppstein** [comment] 2023-07-04 08:14
> I suspect there was a very good reason not to do it like this in the first place

I believe the sequence events was something like the following:

1) In the beginning, the view was that JSON object equality is based on irrelevance of the ordering of keys, and so `keys` was defined as the array of sorted keys.

2) Later, there was an acknowledgement that preserving the order of keys within an object had some value; this naturally gave rise to `keys_unsorted` (so named to avoid backward-compatibility issues).

3) Over time, despite the potential for confusion, a kind of equilibrium has been achieved, with `keys` as homage to the principle that the ordering of keys is irrelevant as far as object equality is concerned; and `keys_unsorted` as  a reflection of jq's respect for the ordering of keys.  In this regard, it is noteworthy that jaq has retained the same `keys`/`keys_unsorted` distinction.

@itchyny - Since no specific documentation enhancements have thus far been proposed in this thread, I think that, in the interests of minimizing confusion, it would be helpful to close this issue and perhaps add the 'not a bug' label.

**Closed** 2023-07-06 02:20 UTC
Labels: support
